# Generated by Django 4.1.3 on 2022-12-08 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('hits', models.PositiveIntegerField(default=0)),
                ('name', models.CharField(max_length=50)),
                ('kind', models.CharField(blank=True, choices=[('announces', '공지사항'), ('benefits', '제휴혜택'), ('inquiries', '문의/건의'), ('petitions', '청원 게시판'), ('serveys', '설문조사')], max_length=15, null=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
    ]
