# Generated by Django 4.1.3 on 2022-11-27 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("announces", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="announce",
            name="kind",
            field=models.CharField(
                blank=True,
                choices=[
                    ("job_employ", "취업"),
                    ("stu_welfare", "복지"),
                    ("facilities", "시설"),
                ],
                max_length=20,
                null=True,
            ),
        ),
    ]
