# Generated by Django 4.1.3 on 2022-12-25 16:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("petitions", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("categories", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="petitionagree",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="agrees",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="petition",
            name="agree",
            field=models.ManyToManyField(
                related_name="petition_agree", to="petitions.petitionagree"
            ),
        ),
        migrations.AddField(
            model_name="petition",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="petitions",
                to="categories.category",
            ),
        ),
        migrations.AddField(
            model_name="petition",
            name="writer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="petitions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
