# Generated by Django 4.1.3 on 2022-11-29 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("petitions", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="petition",
            name="agree",
            field=models.ManyToManyField(
                related_name="petition_agree", to="petitions.agree"
            ),
        ),
    ]
