# Generated by Django 4.1.3 on 2022-12-02 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('petitions', '0003_rename_agree_petitionagree_petitioncomment_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='petition',
            name='comment',
        ),
        migrations.DeleteModel(
            name='PetitionComment',
        ),
    ]
