# Generated by Django 4.1.3 on 2022-12-08 07:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('comments', '0001_initial'),
        ('petitions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='petition',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='petitions.petition'),
        ),
    ]
