# Generated by Django 4.1.3 on 2022-11-29 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("comments", "0002_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="comment",
            name="petitions",
        ),
        migrations.AlterField(
            model_name="comment",
            name="payload",
            field=models.TextField(default="", max_length=150),
        ),
    ]
