# Generated by Django 4.1.3 on 2022-12-02 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inquiries', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inquiryanswer',
            old_name='Inquiry_connected',
            new_name='inquiry_connected',
        ),
        migrations.RemoveField(
            model_name='inquiryanswer',
            name='content',
        ),
        migrations.RemoveField(
            model_name='inquiryanswer',
            name='writer',
        ),
        migrations.AddField(
            model_name='inquiry',
            name='inquiry_content',
            field=models.CharField(default='', max_length=3000),
        ),
    ]
